FROM 172.23.0.14/public/java:openjdk-8u111

COPY /project/target/service-workorder.jar /usr/src/myapp/service-workorder.jar

WORKDIR /usr/src/myapp/

EXPOSE 9026

ENTRYPOINT java -jar service-workorder.jar

